# CargoPulse AI — Feature Engineering

## Objective

Transform cleaned historical logistics data into meaningful,
validated features for:

1. Machine Learning
2. Shipment Simulation
3. Business Impact Analysis

## Input Datasets

- DataCo cleaned dataset
- Smart Logistics cleaned dataset

## Important Principles

- Never modify the cleaned source datasets directly.
- Create working copies before transformation.
- Validate every engineered feature.
- Check prediction-time availability.
- Avoid target leakage.
- Do not fabricate missing information.

In [1]:
import pandas as pd

In [2]:
dataco = pd.read_csv("../datasets/processed/dataco_cleaned.csv")

In [7]:
dataco_fe = dataco.copy()

In [8]:
print("DataCo shape:", dataco_fe.shape)

DataCo shape: (180519, 44)

In [13]:
print(dataco_fe.columns.tolist())

['type', 'days_for_shipping_real', 'days_for_shipment_scheduled', 'benefit_per_order', 'sales_per_customer', 'delivery_status', 'late_delivery_risk', 'category_id', 'category_name', 'customer_city', 'customer_country', 'customer_id', 'customer_segment', 'customer_state', 'customer_zipcode', 'department_id', 'department_name', 'latitude', 'longitude', 'market', 'order_city', 'order_country', 'order_customer_id', 'order_date_dateorders', 'order_id', 'order_item_cardprod_id', 'order_item_discount', 'order_item_discount_rate', 'order_item_id', 'order_item_product_price', 'order_item_profit_ratio', 'order_item_quantity', 'sales', 'order_item_total', 'order_profit_per_order', 'order_region', 'order_state', 'order_status', 'product_card_id', 'product_category_id', 'product_name', 'product_price', 'shipping_date_dateorders', 'shipping_mode']

In [15]:
print(dataco_fe.dtypes)

type                               str
days_for_shipping_real           int64
days_for_shipment_scheduled      int64
benefit_per_order              float64
sales_per_customer             float64
delivery_status                    str
late_delivery_risk               int64
category_id                      int64
category_name                      str
customer_city                      str
customer_country                   str
customer_id                      int64
customer_segment                   str
customer_state                     str
customer_zipcode               float64
department_id                    int64
department_name                    str
latitude                       float64
longitude                      float64
market                             str
order_city                         str
order_country                      str
order_customer_id                int64
order_date_dateorders              str
order_id                         int64
order_item_cardprod_id           int64
order_item_discount            float64
order_item_discount_rate       float64
order_item_id                    int64
order_item_product_price       float64
order_item_profit_ratio        float64
order_item_quantity              int64
sales                          float64
order_item_total               float64
order_profit_per_order         float64
order_region                       str
order_state                        str
order_status                       str
product_card_id                  int64
product_category_id              int64
product_name                       str
product_price                  float64
shipping_date_dateorders           str
shipping_mode                      str
dtype: object

In [17]:
display(dataco_fe.head())

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_profit_per_order,order_region,order_state,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,91.250000,Southeast Asia,Java Occidental,COMPLETE,1360,73,Smart watch,327.75,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,-249.089996,South Asia,Rajastn,PENDING,1360,73,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,-247.779999,South Asia,Rajastn,CLOSED,1360,73,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,22.860001,Oceania,Queensland,COMPLETE,1360,73,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,134.210007,Oceania,Queensland,PENDING_PAYMENT,1360,73,Smart watch,327.75,1/15/2018 11:24,Standard Class

In [22]:
print("DataCo categorical columns:")

for col in [
    "type",
    "delivery_status",
    "shipping_mode",
    "market",
    "order_region",
    "customer_segment"
]:
    print(f"\n{col}:")
    print(dataco_fe[col].value_counts(dropna=False))

DataCo categorical columns:

type:
type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64

delivery_status:
delivery_status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

shipping_mode:
shipping_mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

market:
market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

order_region:
order_region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

customer_segment:
customer_segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

In [24]:
print("DataCo target:")
print(dataco_fe["late_delivery_risk"].value_counts(dropna=False))

DataCo target:
late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [28]:
pd.crosstab(
    dataco_fe["delivery_status"],
    dataco_fe["late_delivery_risk"]
)

late_delivery_risk      0      1
delivery_status
Advance shipping    41592      0
Late delivery           0  98977
Shipping canceled    7754      0
Shipping on time    32196      0

Below code is just to check the datatypes missing value

In [ ]:
print("DataCo date columns:")
print(dataco_fe[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].dtypes)

In [ ]:
print("\nMissing values:")
print(dataco_fe[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].isna().sum())

In [ ]:
print("\nDataCo date samples:")
print(dataco_fe[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].head(10))

In [37]:
dataco_fe["order_date_dateorders"] = pd.to_datetime(
    dataco_fe["order_date_dateorders"]
)

dataco_fe["shipping_date_dateorders"] = pd.to_datetime(
    dataco_fe["shipping_date_dateorders"]
)

In [38]:
print("DataCo date columns:")
print(dataco_fe[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].dtypes)

DataCo date columns:
order_date_dateorders       datetime64[us]
shipping_date_dateorders    datetime64[us]
dtype: object

In [41]:
print("DataCo date types:")
print(
    dataco_fe[
        [
            "order_date_dateorders",
            "shipping_date_dateorders"
        ]
    ].dtypes
)

DataCo date types:
order_date_dateorders       datetime64[us]
shipping_date_dateorders    datetime64[us]
dtype: object

In [45]:
print(dataco_fe[
    [
        "order_date_dateorders",
        "shipping_date_dateorders"
    ]
].head())

  order_date_dateorders shipping_date_dateorders
0   2018-01-31 22:56:00      2018-02-03 22:56:00
1   2018-01-13 12:27:00      2018-01-18 12:27:00
2   2018-01-13 12:06:00      2018-01-17 12:06:00
3   2018-01-13 11:45:00      2018-01-16 11:45:00
4   2018-01-13 11:24:00      2018-01-15 11:24:00

==========================================Now we will create new columns or features ===============================================

==============================================feature 1(order_hour) ==================================================

In [48]:
dataco_fe["order_hour"] = (
    dataco_fe["order_date_dateorders"].dt.hour
)

In [53]:
# print(dataco_fe["order_hour"].value_counts().sort_index())

In [57]:
print(
    "DataCo valid hours:",
    dataco_fe["order_hour"].between(0, 23).all()
)

DataCo valid hours: True

In [58]:
print(dataco_fe[
    [
        "order_date_dateorders",
        "shipping_date_dateorders",
        "order_hour"
    ]
].head())

  order_date_dateorders shipping_date_dateorders  order_hour
0   2018-01-31 22:56:00      2018-02-03 22:56:00          22
1   2018-01-13 12:27:00      2018-01-18 12:27:00          12
2   2018-01-13 12:06:00      2018-01-17 12:06:00          12
3   2018-01-13 11:45:00      2018-01-16 11:45:00          11
4   2018-01-13 11:24:00      2018-01-15 11:24:00          11

In [59]:
print(
    "DataCo valid hours:",
    dataco_fe["order_hour"].between(0, 23).all()
)

DataCo valid hours: True

============================================FEATURE 2(order_day_of_week) ==================================================

In [64]:
dataco_fe["order_day_of_week"] = (
    dataco_fe["order_date_dateorders"].dt.dayofweek
)

In [65]:
print("DataCo day_of_week:")
print(
    dataco_fe["order_day_of_week"]
    .value_counts()
    .sort_index()
)

DataCo day_of_week:
order_day_of_week
0    25786
1    25622
2    25587
3    25752
4    25925
5    25901
6    25946
Name: count, dtype: int64

In [66]:
print(
    "DataCo valid day_of_week:",
    dataco_fe["order_day_of_week"]
    .between(0, 6)
    .all()
)

DataCo valid day_of_week: True

===============================================feature 3(order_month)=========================================================

In [68]:
dataco_fe["order_month"] =(
    dataco_fe["order_date_dateorders"].dt.month
)

In [69]:
print("dataco month")
print(dataco_fe["order_month"].value_counts().sort_index())

dataco month
order_month
1     17979
2     14529
3     15919
4     15435
5     15976
6     15139
7     15922
8     15912
9     15489
10    12955
11    12500
12    12764
Name: count, dtype: int64

In [73]:
print(
    "DataCo valid months:",
    dataco_fe["order_month"]
    .between(1, 12)
    .all()
)

DataCo valid months: True

=================================================Smart Logistics Dataset===============================================================

In [4]:
smart = pd.read_csv("../datasets/processed/smart_logistics_cleaned.csv")

In [10]:
smart_fe = smart.copy()

In [12]:
smart_fe.shape

(1000, 16)

In [14]:
print(smart_fe.columns.tolist())

['timestamp', 'asset_id', 'latitude', 'longitude', 'inventory_level', 'shipment_status', 'temperature', 'humidity', 'traffic_status', 'waiting_time', 'user_transaction_amount', 'user_purchase_frequency', 'logistics_delay_reason', 'asset_utilization', 'demand_forecast', 'logistics_delay']

In [16]:
print(smart_fe.dtypes)

timestamp                      str
asset_id                       str
latitude                   float64
longitude                  float64
inventory_level              int64
shipment_status                str
temperature                float64
humidity                   float64
traffic_status                 str
waiting_time                 int64
user_transaction_amount      int64
user_purchase_frequency      int64
logistics_delay_reason         str
asset_utilization          float64
demand_forecast              int64
logistics_delay              int64
dtype: object

In [20]:
# display(smart_fe.head())

In [21]:
print("Smart Logistics categorical columns:")

for col in [
    "shipment_status",
    "traffic_status",
    "logistics_delay_reason"
]:
    print(f"\n{col}:")
    print(smart_fe[col].value_counts(dropna=False))

Smart Logistics categorical columns:

shipment_status:
shipment_status
Delayed       350
Delivered     338
In Transit    312
Name: count, dtype: int64

traffic_status:
traffic_status
Detour    345
Clear     328
Heavy     327
Name: count, dtype: int64

logistics_delay_reason:
logistics_delay_reason
Weather               267
NaN                   263
Traffic               236
Mechanical Failure    234
Name: count, dtype: int64

In [23]:
print("\nSmart Logistics target:")
print(smart_fe["logistics_delay"].value_counts(dropna=False))

Smart Logistics target:
logistics_delay
1    566
0    434
Name: count, dtype: int64

In [26]:
pd.crosstab(
    smart_fe["shipment_status"],
    smart_fe["logistics_delay"]
)

logistics_delay    0    1
shipment_status
Delayed            0  350
Delivered        220  118
In Transit       214   98

In [ ]:
pd.crosstab(
    smart_fe["logistics_delay_reason"],
    smart_fe["logistics_delay"],
    dropna=False
)

logistics_delay           0    1
logistics_delay_reason
Mechanical Failure      101  133
Traffic                 101  135
Weather                 116  151
NaN                     116  147

Below code is just to check the datatype

In [33]:
print("Smart Logistics timestamp dtype: ")
print(smart_fe["timestamp"].dtype)

Smart Logistics timestamp dtype:
str

In [34]:
print("\n Missing timestamps: ")
print(smart_fe["timestamp"].isna().sum())

 Missing timestamps:
0

In [35]:
print("\n Timestamp samples: ")
print(smart_fe["timestamp"].head(10))

 Timestamp samples:
0    2024-03-20 00:11:14
1    2024-10-30 07:53:51
2    2024-07-29 18:42:48
3    2024-10-28 00:50:54
4    2024-09-27 15:52:58
5    2024-09-17 06:02:15
6    2024-02-05 08:38:56
7    2024-09-28 09:08:23
8    2024-01-18 08:27:04
9    2024-11-09 00:48:26
Name: timestamp, dtype: str

In [36]:
print("\n Timestamp range: ")
print("Smart: ", smart_fe["timestamp"].min())
print("End: ", smart_fe["timestamp"].max())

 Timestamp range:
Smart:  2024-01-01 11:37:57
End:  2024-12-30 20:21:58

In [ ]:
smart_fe["timestamp"] = pd.to_datetime(
    smart_fe["timestamp"]
)

In [42]:
print("\nSmart Logistics timestamp type:")
print(smart_fe["timestamp"].dtype)

Smart Logistics timestamp type:
datetime64[us]

In [43]:
print("\nSmart Logistics missing timestamps after conversion:")

print(
    smart_fe["timestamp"].isna().sum()
)

Smart Logistics missing timestamps after conversion:
0

In [46]:
print(smart_fe["timestamp"].head())

0   2024-03-20 00:11:14
1   2024-10-30 07:53:51
2   2024-07-29 18:42:48
3   2024-10-28 00:50:54
4   2024-09-27 15:52:58
Name: timestamp, dtype: datetime64[us]

=========================================Now we will create new features based on our needs ==========================================

In [ ]:
# ==========================================feature 1(Hour)======================================================

In [47]:
smart_fe["hour"] = (
    smart_fe["timestamp"].dt.hour
)

In [55]:
# print(smart_fe["hour"].value_counts().sort_index())

In [60]:
print(smart_fe[
    [
        "timestamp",
        "hour"
    ]
].head())

            timestamp  hour
0 2024-03-20 00:11:14     0
1 2024-10-30 07:53:51     7
2 2024-07-29 18:42:48    18
3 2024-10-28 00:50:54     0
4 2024-09-27 15:52:58    15

==========================================feature 2(day_of_week)============================================================

In [62]:
smart_fe["day_of_week"]=(
    smart_fe["timestamp"].dt.dayofweek
)

In [63]:
print("\nSmart Logistics day_of_week:")
print(
    smart_fe["day_of_week"]
    .value_counts()
    .sort_index()
)

Smart Logistics day_of_week:
day_of_week
0    153
1    140
2    158
3    135
4    147
5    139
6    128
Name: count, dtype: int64

In [67]:
print(
    "Smart Logistics valid day_of_week:",
    smart_fe["day_of_week"]
    .between(0, 6)
    .all()
)

Smart Logistics valid day_of_week: True

===============================================feature 3(month)=========================================================

In [70]:
smart_fe["month"] = (
    smart_fe["timestamp"].dt.month
)

In [71]:
print("\nSmart Logistics months:")
print(
    smart_fe["month"]
    .value_counts()
    .sort_index()
)

Smart Logistics months:
month
1     92
2     77
3     94
4     86
5     74
6     77
7     86
8     77
9     83
10    83
11    82
12    89
Name: count, dtype: int64

In [72]:
print(
    "Smart Logistics valid months:",
    smart_fe["month"]
    .between(1, 12)
    .all()
)

Smart Logistics valid months: True